x<-function(){1}
x<-function(){1} ; x()
x<-function(z){z} ; x(TRUE) 
x<-1 ; f<-function(){x} ; x<-2 ; f() 
x<-1 ; f<-function(x){x} ; f(TRUE) 
x<-1 ; f<-function(x){a<-1;b<-2;x} ; f(TRUE) 
f<-function(x){g<-function(x) {x} ; g(x) } ; f(TRUE) 
x<-1 ; f<-function(x){a<-1; b<-2; g<-function(x) {b<-3;x} ; g(b) } ; f(TRUE) 
x<-1 ; f<-function(z) { if (z) { x<-2 } ; x } ; x<-3 ; f(FALSE) 
f<-function() {z} ; z<-2 ; f() 
x<-1 ; g<-function() { x<-12 ; f<-function(z) { if (z) { x<-2 } ; x } ; x<-3 ; f(FALSE) } ; g() 
x<-function() { z<-211 ; function(a) { if (a) { z } else { 200 } } } ; f<-x() ; z<-1000 ; f(TRUE) 
f<-function(a=1,b=2,c=3) {TRUE} ; f(,,) 
f<-function(x=2) {x} ; f() 
f<-function(a,b,c=2,d) {c} ; f(1,2,c=4,d=4) 
f<-function(a,b,c=2,d) {c} ; f(1,2,d=8,c=1) 
f<-function(a,b,c=2,d) {c} ; f(1,d=8,2,c=1) 
f<-function(a,b,c=2,d) {c} ; f(d=8,1,2,c=1) 
f<-function(a,b,c=2,d) {c} ; f(d=8,c=1,2,3) 
f<-function(a=10,b,c=20,d=20) {c} ; f(4,3,5,1) 
x<-1 ; z<-TRUE ; f<-function(y=x,a=z,b) { if (z) {y} else {z}} ; f(b=2) 
x<-1 ; z<-TRUE ; f<-function(y=x,a=z,b) { if (z) {y} else {z}} ; f(2) 
x<-1 ; f<-function(x=x) { x } ; f(x=x) 
f<-function(z, x=if (z) 2 else 3) {x} ; f(FALSE) 
f<-function(a,b,c=2,d) {c} ; g <- function() f(d=8,c=1,2,3) ; g() ; g() 
f<-function() { return() } ; f() 
f<-function() { return(2) ; 3 } ; f() 
x <- function(y) { sum(y) } ; f <- function() { x <- 1 ; x(1:10) } ; f() 
f <- sum ; f(1:10) 
x <- function(a,b) { a^b } ; f <- function() { x <- "sum" ; sapply(1, x, 2) } ; f() 
x <- function(a,b) { a^b } ; g <- function() { x <- "sum" ; f <- function() { sapply(1, x, 2) } ; f() }  ; g() 
x <- function(a,b) { a^b } ; f <- function() { x <- 211 ; sapply(1, x, 2) } ; f() 
x <- function(a,b) { a^b } ; dummy <- sum ; f <- function() { x <- "dummy" ; sapply(1, x, 2) } ; f() 
x <- function(a,b) { a^b } ; dummy <- sum ; f <- function() { x <- "dummy" ; dummy <- 200 ; sapply(1, x, 2) } ; f() 
x<-function(){1} ; x(y=1) 
x<-function(){1} ; x(1) 
x<-function(a){1} ; x(1,) 
x<-function(){1} ; x(y=sum(1:10)) 
myapp <- function(f, x, y) { f(x,y) } ; myapp(function(x,y) { x + y }, 1, 2) ; myapp(sum, 1, 2) 
myapp <- function(f, x, y) { f(x,y) } ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; myapp(f = sum, x = 1, y = 2) 
myapp <- function(f, x, y) { f(x,y) } ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; myapp(f = sum, x = 1, y = 2) ; myapp(f = c, y = 10, x = 3) 
myapp <- function(f, x, y) { f(x,y) } ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; myapp(f = sum, x = 1, y = 2) ; myapp(f = function(x,y) { x - y }, y = 10, x = 3) 
myapp <- function(f, x, y) { f(x,y) } ; g <- function(x,y) { x + y } ; myapp(f = g, y = 1, x = 2) ; myapp(f = sum, x = 1, y = 2) ; myapp(f = g, y = 10, x = 3) ;  myapp(f = g, y = 11, x = 2) 
f<-function(i) { if(i==1) { 1 } else { j<-i-1 ; f(j) } } ; f(10) 
f<-function(i) { if(i==1) { 1 } else { f(i-1) } } ; f(10) 
f<-function(i) { if(i<=1) 1 else i*f(i-1) } ; f(10) 
f<-function(i) { if(i<=1L) 1L else i*f(i-1L) } ; f(10L) 
f<-function(i) { if(i<=1) 1 else i*f(i-1) } ; g<-function(n, f, a) { if (n==1) { f(a) } else { f(a) ; g(n-1, f, a) } } ; g(100,f,120) 
f<-function(i) { if (i==1) { 1 } else if (i==2) { 1 } else { f(i-1) + f(i-2) } } ; f(10) 
f<-function(i) { if (i==1L) { 1L } else if (i==2L) { 1L } else { f(i-1L) + f(i-2L) } } ; f(10L) 
