f<-function(i) { if(i==1) { 1 } else { j<-i-1 ; f(j) } } ; f(10) 
f<-function(i) { if(i==1) { i } } ; f(1) ; f(2) 
f<-function(i) {i} ; f(1) ; f(2) 
f<-function() { 1:5 } ; f(); f() 
f<-function() { length(c(1,2)) } ; f(); f() 
f<-function() { if (!1) TRUE } ; f(); f() 
f<-function() { if (1) TRUE } ; f(); f() 
f<-function() { if (!TRUE) 1 } ; f(); f() 
f<-function() { if (if (1) {TRUE} else {FALSE} ) 1 } ; f(); f() 
f<-function() { logical(0) } ; f(); f() 
f<-function(i) { if (FALSE) { i } } ; f(2) ; f(1) 
f<-function(i) { if (TRUE) { i } } ; f(2) ; f(1) 
f<-function(i) { i ; if (FALSE) { 1 } else { i } } ; f(2) ; f(1) 
f<-function(i) { i ; if (TRUE) { 1 } else { i } } ; f(2) ; f(1) 
f<-function(i) { if(i==1) { 1 } else { i } } ; f(2) ; f(2) 
f<-function(i) { if(i==1) { 1 } else { i } } ; f(2) ; f(1) 
f<-function() { x<-210 ; repeat { x <- x + 1 ; break } ; x } ; f() ; f() 
f<-function() { x<-1 ; repeat { x <- x + 1 ; if (x > 11) { break } } ; x } ; f(); f() 
f<-function() { x<-1 ; repeat { x <- x + 1 ; if (x <= 11) { next } else { break } ; x <- 1024 } ; x } ; f() ; f() 
f<-function() { x<-1 ; while(TRUE) { x <- x + 1 ; if (x > 11) { break } } ; x } ; f(); f() 
f<-function() { x<-1 ; while(TRUE) { x <- x + 1 ; if (x > 11) { break } } ; x } ; f(); f() 
f<-function() { x<-1 ; while(x <= 10) { x<-x+1 } ; x } ; f(); f() 
f<-function() { x<-1 ; for(i in 1:10) { x<-x+1 } ; x } ; f(); f() 
