f<-function(i) { if(i==1) { 1 } else { j<-i-1 ; "TOKEN" ; f(j) } } ; "TOKEN" ; f(10) 
f<-function(i) { if(i==1) { i } } ; "TOKEN" ; f(1) ; "TOKEN" ; f(2) 
f<-function(i) {i} ; "TOKEN" ; f(1) ; "TOKEN" ; f(2) 
f<-function() { 1:5 } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { length(c(1,2)) } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { if (!1) TRUE } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { if (1) TRUE } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { if (!TRUE) 1 } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { if (if (1) {TRUE} else {FALSE} ) 1 } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { logical(0) } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function(i) { if (FALSE) { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(1) 
f<-function(i) { if (TRUE) { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(1) 
f<-function(i) { i ; "TOKEN" ; if (FALSE) { 1 } else { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(1) 
f<-function(i) { i ; "TOKEN" ; if (TRUE) { 1 } else { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(1) 
f<-function(i) { if(i==1) { 1 } else { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(2) 
f<-function(i) { if(i==1) { 1 } else { i } } ; "TOKEN" ; f(2) ; "TOKEN" ; f(1) 
f<-function() { x<-210 ; "TOKEN" ; repeat { x <- x + 1 ; "TOKEN" ; break } ; "TOKEN" ; x } ; "TOKEN" ; f() ; "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; repeat { x <- x + 1 ; "TOKEN" ; if (x > 11) { break } } ; "TOKEN" ; x } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; repeat { x <- x + 1 ; "TOKEN" ; if (x <= 11) { next } else { break } ; "TOKEN" ; x <- 1024 } ; "TOKEN" ; x } ; "TOKEN" ; f() ; "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; while(TRUE) { x <- x + 1 ; "TOKEN" ; if (x > 11) { break } } ; "TOKEN" ; x } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; while(TRUE) { x <- x + 1 ; "TOKEN" ; if (x > 11) { break } } ; "TOKEN" ; x } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; while(x <= 10) { x<-x+1 } ; "TOKEN" ; x } ; "TOKEN" ; f(); "TOKEN" ; f() 
f<-function() { x<-1 ; "TOKEN" ; for(i in 1:10) { x<-x+1 } ; "TOKEN" ; x } ; "TOKEN" ; f(); "TOKEN" ; f() 
