x<-function(){1}
x<-function(){1} ; "TOKEN" ; x()
x<-function(z){z} ; "TOKEN" ; x(TRUE) 
x<-1 ; "TOKEN" ; f<-function(){x} ; "TOKEN" ; x<-2 ; "TOKEN" ; f() 
x<-1 ; "TOKEN" ; f<-function(x){x} ; "TOKEN" ; f(TRUE) 
x<-1 ; "TOKEN" ; f<-function(x){a<-1; "TOKEN" ;b<-2; "TOKEN" ;x} ; "TOKEN" ; f(TRUE) 
f<-function(x){g<-function(x) {x} ; "TOKEN" ; g(x) } ; "TOKEN" ; f(TRUE) 
x<-1 ; "TOKEN" ; f<-function(x){a<-1; "TOKEN" ; b<-2; "TOKEN" ; g<-function(x) {b<-3; "TOKEN" ;x} ; "TOKEN" ; g(b) } ; "TOKEN" ; f(TRUE) 
x<-1 ; "TOKEN" ; f<-function(z) { if (z) { x<-2 } ; "TOKEN" ; x } ; "TOKEN" ; x<-3 ; "TOKEN" ; f(FALSE) 
f<-function() {z} ; "TOKEN" ; z<-2 ; "TOKEN" ; f() 
x<-1 ; "TOKEN" ; g<-function() { x<-12 ; "TOKEN" ; f<-function(z) { if (z) { x<-2 } ; "TOKEN" ; x } ; "TOKEN" ; x<-3 ; "TOKEN" ; f(FALSE) } ; "TOKEN" ; g() 
x<-function() { z<-211 ; "TOKEN" ; function(a) { if (a) { z } else { 200 } } } ; "TOKEN" ; f<-x() ; "TOKEN" ; z<-1000 ; "TOKEN" ; f(TRUE) 
f<-function(a=1,b=2,c=3) {TRUE} ; "TOKEN" ; f(,,) 
f<-function(x=2) {x} ; "TOKEN" ; f() 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; f(1,2,c=4,d=4) 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; f(1,2,d=8,c=1) 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; f(1,d=8,2,c=1) 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; f(d=8,1,2,c=1) 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; f(d=8,c=1,2,3) 
f<-function(a=10,b,c=20,d=20) {c} ; "TOKEN" ; f(4,3,5,1) 
x<-1 ; "TOKEN" ; z<-TRUE ; "TOKEN" ; f<-function(y=x,a=z,b) { if (z) {y} else {z}} ; "TOKEN" ; f(b=2) 
x<-1 ; "TOKEN" ; z<-TRUE ; "TOKEN" ; f<-function(y=x,a=z,b) { if (z) {y} else {z}} ; "TOKEN" ; f(2) 
x<-1 ; "TOKEN" ; f<-function(x=x) { x } ; "TOKEN" ; f(x=x) 
f<-function(z, x=if (z) 2 else 3) {x} ; "TOKEN" ; f(FALSE) 
f<-function(a,b,c=2,d) {c} ; "TOKEN" ; g <- function() f(d=8,c=1,2,3) ; "TOKEN" ; g() ; "TOKEN" ; g() 
f<-function() { return() } ; "TOKEN" ; f() 
f<-function() { return(2) ; "TOKEN" ; 3 } ; "TOKEN" ; f() 
x <- function(y) { sum(y) } ; "TOKEN" ; f <- function() { x <- 1 ; "TOKEN" ; x(1:10) } ; "TOKEN" ; f() 
f <- sum ; "TOKEN" ; f(1:10) 
x <- function(a,b) { a^b } ; "TOKEN" ; f <- function() { x <- "sum" ; "TOKEN" ; sapply(1, x, 2) } ; "TOKEN" ; f() 
x <- function(a,b) { a^b } ; "TOKEN" ; g <- function() { x <- "sum" ; "TOKEN" ; f <- function() { sapply(1, x, 2) } ; "TOKEN" ; f() }  ; "TOKEN" ; g() 
x <- function(a,b) { a^b } ; "TOKEN" ; f <- function() { x <- 211 ; "TOKEN" ; sapply(1, x, 2) } ; "TOKEN" ; f() 
x <- function(a,b) { a^b } ; "TOKEN" ; dummy <- sum ; "TOKEN" ; f <- function() { x <- "dummy" ; "TOKEN" ; sapply(1, x, 2) } ; "TOKEN" ; f() 
x <- function(a,b) { a^b } ; "TOKEN" ; dummy <- sum ; "TOKEN" ; f <- function() { x <- "dummy" ; "TOKEN" ; dummy <- 200 ; "TOKEN" ; sapply(1, x, 2) } ; "TOKEN" ; f() 
x<-function(){1} ; "TOKEN" ; x(y=1) 
x<-function(){1} ; "TOKEN" ; x(1) 
x<-function(a){1} ; "TOKEN" ; x(1,) 
x<-function(){1} ; "TOKEN" ; x(y=sum(1:10)) 
myapp <- function(f, x, y) { f(x,y) } ; "TOKEN" ; myapp(function(x,y) { x + y }, 1, 2) ; "TOKEN" ; myapp(sum, 1, 2) 
myapp <- function(f, x, y) { f(x,y) } ; "TOKEN" ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; "TOKEN" ; myapp(f = sum, x = 1, y = 2) 
myapp <- function(f, x, y) { f(x,y) } ; "TOKEN" ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; "TOKEN" ; myapp(f = sum, x = 1, y = 2) ; "TOKEN" ; myapp(f = c, y = 10, x = 3) 
myapp <- function(f, x, y) { f(x,y) } ; "TOKEN" ; myapp(f = function(x,y) { x + y }, y = 1, x = 2) ; "TOKEN" ; myapp(f = sum, x = 1, y = 2) ; "TOKEN" ; myapp(f = function(x,y) { x - y }, y = 10, x = 3) 
myapp <- function(f, x, y) { f(x,y) } ; "TOKEN" ; g <- function(x,y) { x + y } ; "TOKEN" ; myapp(f = g, y = 1, x = 2) ; "TOKEN" ; myapp(f = sum, x = 1, y = 2) ; "TOKEN" ; myapp(f = g, y = 10, x = 3) ; "TOKEN" ;  myapp(f = g, y = 11, x = 2) 
f<-function(i) { if(i==1) { 1 } else { j<-i-1 ; "TOKEN" ; f(j) } } ; "TOKEN" ; f(10) 
f<-function(i) { if(i==1) { 1 } else { f(i-1) } } ; "TOKEN" ; f(10) 
f<-function(i) { if(i<=1) 1 else i*f(i-1) } ; "TOKEN" ; f(10) 
f<-function(i) { if(i<=1L) 1L else i*f(i-1L) } ; "TOKEN" ; f(10L) 
f<-function(i) { if(i<=1) 1 else i*f(i-1) } ; "TOKEN" ; g<-function(n, f, a) { if (n==1) { f(a) } else { f(a) ; "TOKEN" ; g(n-1, f, a) } } ; "TOKEN" ; g(100,f,120) 
f<-function(i) { if (i==1) { 1 } else if (i==2) { 1 } else { f(i-1) + f(i-2) } } ; "TOKEN" ; f(10) 
f<-function(i) { if (i==1L) { 1L } else if (i==2L) { 1L } else { f(i-1L) + f(i-2L) } } ; "TOKEN" ; f(10L) 
