5L:10L 
5L:(0L-5L) 
1:10 
1:(0-10) 
1L:(0-10) 
1:(0L-10L) 
(0-12):1.5 
1.5:(0-12) 
(0-1.5):(0-12) 
10:1 
(0-5):(0-9) 
seq(1,10) 
seq(10,1) 
seq(from=1,to=3) 
seq(to=-1,from=-10) 
seq(length.out=13.4) 
seq(length.out=0) 
seq(length.out=1) 
seq(along.with=10) 
seq(along.with=NA) 
seq(along.with=1:10) 
seq(along.with=-3:-5) 
seq(from=1.4) 
seq(from=1.7) 
seq(from=10:12) 
seq(from=c(TRUE, FALSE)) 
seq(from=TRUE, to=TRUE, length.out=0) 
seq(from=10.5, to=15.4, length.out=4) 
seq(from=11, to=12, length.out=2) 
seq(from=1,to=3,by=1) 
seq(from=-10,to=-5,by=2) 
seq(from=-10.4,to=-5.8,by=2.1) 
seq(from=3L,to=-2L,by=-4.2) 
seq(along=c(10,11,12)) 
integer() 
double() 
logical() 
double(3) 
logical(3L) 
character(1L) 
max((-1):100) 
max(1:10, 100:200, c(4.0, 5.0)) 
max(1:10, 100:200, c(4.0, 5.0), c(TRUE,FALSE,NA)) 
max(2L, 4L) 
max() 
max(c("hi","abbey","hello")) 
max("hi","abbey","hello") 
min((-1):100) 
min(1:10, 100:200, c(4.0, -5.0)) 
min(1:10, 100:200, c(4.0, 5.0), c(TRUE,FALSE,NA)) 
min(2L, 4L) 
min() 
min(c("hi","abbey","hello")) 
min("hi","abbey","hello") 
min("hi",100) 
rep(1,3) 
rep(1:3,2) 
rep(c(1,2),0) 
rep(1:3, length.out=4) 
rep(1:3, length.out=NA) 
rep(as.raw(14), 4) 
x <- as.raw(11) ; names(x) <- c("X") ; rep(x, 3) 
x <- as.raw(c(11,12)) ; names(x) <- c("X","Y") ; rep(x, 2) 
x <- c(TRUE,NA) ; names(x) <- c("X",NA) ; rep(x, length.out=3) 
x <- 1L ; names(x) <- c("X") ; rep(x, times=2) 
x <- 1 ; names(x) <- c("X") ; rep(x, times=0) 
x <- 1+1i ; names(x) <- c("X") ; rep(x, times=2) 
x <- c(1+1i,1+2i) ; names(x) <- c("X") ; rep(x, times=2) 
x <- c("A","B") ; names(x) <- c("X") ; rep(x, length.out=3) 
c(1.0,1L) 
c(1L,1.0) 
c(TRUE,1L,1.0,list(3,4)) 
c(TRUE,1L,1.0,list(3,list(4,5))) 
c() 
c(NULL,NULL) 
c(NULL,1,2,3) 
f <- function(x,y) { c(x,y) } ; f(1,1) ; f(1, TRUE) 
f <- function(x,y) { c(x,y) } ; f(1,1) ; f(1, TRUE) ; f(NULL, NULL) 
c("hello", "hi") 
c(1+1i, as.raw(10)) 
c(as.raw(10), as.raw(20)) 
c(x=1,y=2) 
c(x=1,2) 
x <- 1:2 ; names(x) <- c("A",NA) ; c(x,test=x) 
c(a=1,b=2:3,list(x=FALSE))  
c(1,z=list(1,b=22,3)) 
is.na(c(1,2,3,4)) 
is.na(1[10]) 
is.na(c(1[10],2[10],3)) 
is.na(list(1[10],1L[10],list(),integer())) 
as.integer(c(1,2,3)) 
as.integer(list(c(1),2,3)) 
as.integer(list(integer(),2,3)) 
as.integer(list(list(1),2,3)) 
as.integer(list(1,2,3,list())) 
m<-matrix(1:6, nrow=3) ; as.integer(m) 
m<-matrix(1:6, nrow=3) ; as.vector(m, "any") 
m<-matrix(1:6, nrow=3) ; as.vector(mode = "integer", x=m) 
as.vector(list(1,2,3), mode="integer") 
as.double("1.27") 
as.double(1L) 
as.double("TRUE") 
as.double(c("1","hello")) 
as.character(1L) 
as.character(TRUE) 
as.character(1:3) 
as.character(NULL) 
as.character(list(c("hello", "hi"))) 
as.character(list(list(c("hello", "hi")))) 
as.character(list(1,2,3)) 
as.character(list(c(2L, 3L))) 
as.character(list(c(2L, 3L, 5L))) 
as.raw(list(1,2,3)) 
as.raw(list("1", 2L, 3.4)) 
as.raw(c(1,1000,NA)) 
as.logical(1) 
as.logical("false") 
as.logical("dummy") 
as.complex(0) 
as.complex(TRUE) 
as.complex("1+5i") 
as.complex("1e10+5i") 
as.complex("-1+5i") 
as.complex("-1-5i") 
as.complex("-.1e10+5i") 
as.complex("1e-2+3i") 
as.complex("+.1e+2-3i") 
as.complex(as.character(c(1+1i,1+1i))) 
as.complex(as.double(c(1+1i,1+1i))) 
as.complex(as.integer(c(1+1i,1+1i))) 
as.complex(as.logical(c(1+1i,1+1i))) 
as.complex(as.raw(c(1+1i,1+1i))) 
as.double(as.logical(c(10,10))) 
as.integer(as.logical(-1:1)) 
as.raw(as.logical(as.raw(c(1,2)))) 
as.character(as.double(1:5)) 
as.character(as.complex(1:2)) 
m <- matrix(1:6, nrow=2) ; as.double(m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; as.integer(m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; as.logical(m) 
x <- 1:2; names(x) <- c("hello","hi") ; as.double(x) 
x <- c(1,2); names(x) <- c("hello","hi") ; as.integer(x) 
x <- c(0,2); names(x) <- c("hello","hi") ; as.logical(x) 
sum(1:6, 3, 4) 
sum(1:6, 3L, TRUE) 
sum() 
sum(0, 1[3]) 
sum(na.rm=FALSE, 0, 1[3]) 
sum(0, na.rm=FALSE, 1[3]) 
sum(0, 1[3], na.rm=FALSE) 
sum(0, 1[3], na.rm=TRUE) 
`sum`(1:10) 
lapply(1:3, function(x) { 2*x }) 
lapply(1:3, function(x,y) { x*y }, 2) 
sapply(1:3,function(x){x*2}) 
sapply(c(1,2,3),function(x){x*2}) 
sapply(list(1,2,3),function(x){x*2}) 
sapply(1:3, function(x) { if (x==1) { 1 } else if (x==2) { integer() } else { TRUE } }) 
f<-function(g) { sapply(1:3, g) } ; f(function(x) { x*2 }) 
f<-function(g) { sapply(1:3, g) } ; f(function(x) { x*2 }) ; f(function(x) { TRUE }) 
sapply(1:3, function(x) { if (x==1) { list(1) } else if (x==2) { list(NULL) } else { list(2) } }) 
sapply(1:3, function(x) { if (x==1) { list(1) } else if (x==2) { list(NULL) } else { list() } }) 
f<-function() { x<-2 ; sapply(1, function(i) { x }) } ; f() 
sapply(1:3, length) 
f<-length; sapply(1:3, f) 
sapply(1:3, `-`, 2) 
sapply(1:3, "-", 2) 
sapply(1:2, function(i) { if (i==1) { as.raw(0) } else { as.raw(10) } }) 
sapply(1:2, function(i) { if (i==1) { as.raw(0) } else { "hello" }} ) 
sapply(1:2, function(i) { if (i==1) { as.raw(0) } else { 5+10i } }) 
sapply(1:3, function(i) { list(1,2) }) 
sapply(1:3, function(i) { if (i < 3) { list(1,2) } else { c(11,12) } }) 
sapply(1:3, function(i) { if (i < 3) { c(1+1i,2) } else { c(11,12) } }) 
( sapply(1:3, function(i) { if (i < 3) { list(xxx=1) } else {list(zzz=2)} })) 
( sapply(1:3, function(i) { list(xxx=1:i) } )) 
sapply(1:3, function(i) { if (i < 3) { list(xxx=1) } else {list(2)} }) 
( sapply(1:3, function(i) { if (i < 3) { c(xxx=1) } else {c(2)} })) 
f <- function() { lapply(c(X="a",Y="b"), function(x) { c(a=x) })  } ; f() 
f <- function() { sapply(c(1,2), function(x) { c(a=x) })  } ; f() 
f <- function() { sapply(c(X=1,Y=2), function(x) { c(a=x) })  } ; f() 
f <- function() { sapply(c("a","b"), function(x) { c(a=x) })  } ; f() 
f <- function() { sapply(c(X="a",Y="b"), function(x) { c(a=x) })  } ; f() 
sapply(c("a","b","c"), function(x) { x }) 
cat("hi",1:3,"hello") 
cat("hi",NULL,"hello",sep="-") 
cat("hi",integer(0),"hello",sep="-") 
cat("hi",1[2],"hello",sep="-") 
m <- matrix(as.character(1:6, nrow=2)) ; cat(m) 
cat(sep=" ", "hello") 
outer(1:3,1:2) 
outer(1:3,1:2,"*") 
outer(1, 3, "-") 
outer(1:3,1:2, function(x,y,z) { x*y*z }, 10) 
outer(1:2, 1:3, "<") 
outer(1:2, 1:3, '<') 
`+`(1,2) 
`-`(1,2) 
`*`(1,2) 
`/`(1,2) 
`%/%`(1,2) 
`%%`(1,2) 
`^`(1,2) 
`!`(TRUE) 
`||`(TRUE, FALSE) 
`&&`(TRUE, FALSE) 
`|`(TRUE, FALSE) 
`&`(TRUE, FALSE) 
`%o%`(3,5) 
`%*%`(3,5) 
x <- `+` ; x(2,3) 
x <- `+` ; f <- function() { x <- 1 ; x(2,3) } ; f() 
m <- matrix(1:6, nrow=2) ;  upper.tri(m, diag=TRUE) 
m <- matrix(1:6, nrow=2) ;  upper.tri(m, diag=FALSE) 
m <- matrix(1:6, nrow=2) ;  lower.tri(m, diag=TRUE) 
m <- matrix(1:6, nrow=2) ;  lower.tri(m, diag=FALSE) 
upper.tri(1:3, diag=TRUE) 
upper.tri(1:3, diag=FALSE) 
lower.tri(1:3, diag=TRUE) 
lower.tri(1:3, diag=FALSE) 
m <- { matrix( as.character(1:6), nrow=2 ) } ; diag(m) <- c(1,2) ; m 
m <- { matrix( (1:6) * (1+3i), nrow=2 ) } ; diag(m) <- c(1,2) ; m 
m <- { matrix( as.raw(11:16), nrow=2 ) } ; diag(m) <- c(as.raw(1),as.raw(2)) ; m 
m <- matrix(1:6, nrow=3) ; diag(m) <- c(1,2) ; m 
x <- (m <- matrix(1:6, nrow=3)) ; diag(m) <- c(1,2) ; x 
m <- matrix(1:6, nrow=3) ; f <- function() { diag(m) <- c(100,200) } ; f() ; m 
dim(1) 
dim(1:3) 
m <- matrix(1:6, nrow=3) ; dim(m) 
nrow(1) 
nrow(1:3) 
m <- matrix(1:6, nrow=3) ; nrow(m) 
ncol(1) 
ncol(1:3) 
m <- matrix(1:6, nrow=3) ; ncol(m) 
x <- 1:2 ; dim(x) <- c(1,2) ; x 
x <- 1:2 ; dim(x) <- c(1,3) ; x 
x <- 1:2 ; dim(x) <- c(1,NA) ; x 
x <- 1:2 ; dim(x) <- c(1,-1) ; x 
x <- 1:2 ; dim(x) <- integer() ; x 
x <- 1:2 ; attr(x, "dim") <- c(2,1) ; x 
cumsum(1:10) 
cumsum(c(1,2,3)) 
cumsum(rep(1e308, 3) ) 
cumsum(NA) 
cumsum(c(1e308, 1e308, NA, 1, 2)) 
cumsum(c(2000000000L, 2000000000L)) 
cumsum(c(2000000000L, NA, 2000000000L)) 
cumsum(as.logical(-2:2)) 
cumsum((1:6)*(1+1i)) 
cumsum(as.raw(1:6)) 
cumsum(c(1,2,3,0/0,5)) 
cumsum(c(1,0/0,5+1i)) 
which(c(TRUE, FALSE, NA, TRUE)) 
which(logical()) 
which(c(a=TRUE,b=FALSE,c=TRUE)) 
m <- matrix(1:6, nrow=2) ; colMeans(m) 
m <- matrix(1:6, nrow=2) ; colSums(na.rm = FALSE, x = m) 
m <- matrix(1:6, nrow=2) ; rowMeans(x = m, na.rm = TRUE) 
m <- matrix(1:6, nrow=2) ; rowSums(x = m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; colMeans(m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; colSums(m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; rowMeans(m) 
m <- matrix(c(1,2,3,4,5,6), nrow=2) ; rowSums(m) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; rowSums(m) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; rowSums(m, na.rm = TRUE) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; rowMeans(m, na.rm = TRUE) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; colSums(m) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; colSums(na.rm = TRUE, m) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; colMeans(m) 
m <- matrix(c(NA,2,3,4,NA,6), nrow=2) ; colMeans(m, na.rm = TRUE) 
colSums(matrix(as.complex(1:6), nrow=2)) 
colSums(matrix((1:6)*(1+1i), nrow=2)) 
colMeans(matrix(as.complex(1:6), nrow=2)) 
colMeans(matrix((1:6)*(1+1i), nrow=2)) 
rowSums(matrix(as.complex(1:6), nrow=2)) 
rowSums(matrix((1:6)*(1+1i), nrow=2)) 
rowMeans(matrix(as.complex(1:6), nrow=2)) 
rowMeans(matrix((1:6)*(1+1i), nrow=2)) 
o <- outer(1:3, 1:4, "<") ; colSums(o) 
nchar(c("hello", "hi")) 
nchar(c("hello", "hi", 10, 130)) 
nchar(c(10,130)) 
strsplit("helloh", "h", fixed=TRUE) 
strsplit( c("helloh", "hi"), c("h",""), fixed=TRUE) 
strsplit("helloh", "", fixed=TRUE) 
strsplit("helloh", "h") 
strsplit( c("helloh", "hi"), c("h","")) 
strsplit("ahoj", split="") [[c(1,2)]] 
paste(1:2, 1:3, FALSE, collapse=NULL) 
paste(1:2, 1:3, FALSE, collapse="-", sep="+") 
paste() 
paste(sep="") 
a <- as.raw(200) ; b <- as.raw(255) ; paste(a, b) 
substr("123456", start=2, stop=4) 
substr("123456", start=2L, stop=4L) 
substr("123456", start=2.8, stop=4) 
substr(c("hello", "bye"), start=c(1,2,3), stop=4) 
substr("fastr", start=NA, stop=2) 
substring("123456", first=2, last=4) 
substring("123456", first=2.8, last=4) 
substring(c("hello", "bye"), first=c(1,2,3), last=4) 
substring("fastr", first=NA, last=2) 
order(1:3) 
order(3:1) 
order(c(1,1,1), 3:1) 
order(c(1,1,1), 3:1, decreasing=FALSE) 
order(c(1,1,1), 3:1, decreasing=TRUE, na.last=TRUE) 
order(c(1,1,1), 3:1, decreasing=TRUE, na.last=NA) 
order(c(1,1,1), 3:1, decreasing=TRUE, na.last=FALSE) 
order() 
order(c(NA,NA,1), c(2,1,3)) 
order(c(NA,NA,1), c(1,2,3)) 
order(c(1,2,3,NA)) 
order(c(1,2,3,NA), na.last=FALSE) 
order(c(1,2,3,NA), na.last=FALSE, decreasing=TRUE) 
order(c(0/0, -1/0, 2)) 
order(c(0/0, -1/0, 2), na.last=NA) 
log(1) 
m <- matrix(1:4, nrow=2) ; log10(m) 
x <- c(a=1, b=10) ; c(log(x), log10(x), log2(x)) 
sqrt(c(a=9,b=81)) 
exp(c(1+1i,-2-3i)) 
exp(1+2i) 
abs((-1-0i)/(0+0i)) 
abs((-0-1i)/(0+0i)) 
abs(NA+0.1) 
abs(0/0) 
exp(-abs((0+1i)/(0+0i))) 
floor(c(0.2,-3.4)) 
ceiling(c(0.2,-3.4,NA,0/0,1/0)) 
toupper(c("hello","bye")) 
tolower(c("Hello","ByE")) 
tolower(1E100) 
toupper(1E100) 
tolower(c()) 
tolower(NA) 
m <- matrix("hi") ; toupper(m) 
toupper(c(a="hi", "hello")) 
tolower(c(a="HI", "HELlo")) 
typeof(1) 
typeof(1L) 
typeof(sum) 
typeof(function(){}) 
typeof("hi") 
gsub("a","aa", "prague alley", fixed=TRUE) 
sub("a","aa", "prague alley", fixed=TRUE) 
gsub("a","aa", "prAgue alley", fixed=TRUE) 
gsub("a","aa", "prAgue alley", fixed=TRUE, ignore.case=TRUE) 
gsub("h","", c("hello", "hi", "bye"), fixed=TRUE) 
gsub("a","aa", "prague alley") 
sub("a","aa", "prague alley") 
gsub("a","aa", "prAgue alley") 
gsub("a","aa", "prAgue alley", ignore.case=TRUE) 
gsub("h","", c("hello", "hi", "bye") 
gsub("([a-e])","11", "prague alley") 
x <- 1:4 ; length(x) <- 2 ; x 
x <- 1:2 ; length(x) <- 4 ; x 
x <- 1:2 ; z <- (length(x) <- 4) ; z 
length(c(z=1:4)) 
x <- 1:2 ; names(x) <- c("hello", "hi"); names(x) 
x <- 1:2 ; names(x) <- c("hello"); names(x) 
x <- 1:2; names(x) <- c("hello", "hi") ; x 
x <- c(1,9); names(x) <- c("hello","hi") ; sqrt(x) 
x <- c(1,9); names(x) <- c("hello","hi") ; is.na(x) 
x <- c(1,NA); names(x) <- c("hello","hi") ; cumsum(x) 
x <- c(1,NA); names(x) <- c(NA,"hi") ; cumsum(x) 
x <- c(1,2); names(x) <- c("A", "B") ; x + 1 
x <- 1:2; names(x) <- c("A", "B") ; y <- c(1,2,3,4) ; names(y) <- c("X", "Y", "Z") ; x + y 
x <- 1:2; names(x) <- c("A", "B") ; abs(x) 
rev(c(1+1i, 2+2i)) 
rev(1:3) 
f <- function() { assign("x", 1) ; x } ; f() 
f <- function() { x <- 2 ; g <- function() { x <- 3 ; assign("x", 1, inherits=FALSE) ; x } ; g() } ; f() 
f <- function() { x <- 2 ; g <- function() { assign("x", 1, inherits=FALSE) } ; g() ; x } ; f() 
f <- function() { x <- 2 ; g <- function() { assign("x", 1, inherits=TRUE) } ; g() ; x } ; f() 
f <- function() {  g <- function() { assign("x", 1, inherits=TRUE) } ; g() } ; f() ; x 
x <- 3 ; g <- function() { x } ; f <- function() { assign("x", 2) ; g() } ; f() 
x <- 3 ; f <- function() { assign("x", 2) ; g <- function() { x } ; g() } ; f() 
h <- function() { x <- 3 ; g <- function() { x } ; f <- function() { assign("x", 2) ; g() } ; f() }  ; h() 
h <- function() { x <- 3  ; f <- function() { assign("x", 2) ; g <- function() { x } ; g() } ; f() }  ; h() 
x <- 3 ; h <- function() { g <- function() { x } ; f <- function() { assign("x", 2, inherits=TRUE) } ; f() ; g() }  ; h() 
x <- 3 ; h <- function(s) { if (s == 2) { assign("x", 2) } ; x }  ; h(1) ; h(2) 
x <- 3 ; h <- function(s) { y <- x ; if (s == 2) { assign("x", 2) } ; c(y,x) }  ; c(h(1),h(2)) 
f <- function()  { as.environment(-1) } ; f() 
emptyenv() 
x <- 3 ; f <- function() { exists("x") } ; f() 
x <- 3 ; f <- function() { exists("x", inherits=FALSE) } ; f() 
h <- new.env(parent=emptyenv()) ; assign("x", 1, h) ; assign("y", 2, h) ; ls(h) 
f <- function() { x <- 2 ; get("x") } ; f() 
x <- 3 ; f <- function() { get("x") } ; f() 
x <- 3 ; f <- function() { x <- 2 ; get("x") } ; f() 
x <- 3 ; f <- function() { x <- 2; h <- function() {  get("x") }  ; h() } ; f() 
x <- 3 ; f <- function() { assign("x", 4) ; h <- function(s=1) { if (s==2) { x <- 5 } ; x } ; h() } ; f() 
f <- function() { assign("x", 2, inherits=TRUE) ; assign("x", 1) ; h <- function() { x } ; h() } ; f() 
x <- 3 ; g <- function() { if (FALSE) { x <- 2 } ; f <- function() { h <- function() { x } ; h() } ; f() } ; g() 
x <- 3 ; gg <- function() {  g <- function() { if (FALSE) { x <- 2 } ; f <- function() { h <- function() { x } ; h() } ; f() } ; g() } ; gg() 
h <- function() { x <- 2 ; f <- function() { if (FALSE) { x <- 1 } ; g <- function() { x } ; g() } ; f() } ; h() 
x <- function(){3} ; f <- function() { assign("x", function(){4}) ; h <- function(s=1) { if (s==2) { x <- 5 } ; x() } ; h() } ; f() 
f <- function() { assign("x", function(){2}, inherits=TRUE) ; assign("x", function(){1}) ; h <- function() { x() } ; h() } ; f() 
x <- function(){3} ; g <- function() { if (FALSE) { x <- 2 } ; f <- function() { h <- function() { x() } ; h() } ; f() } ; g() 
x <- function(){3} ; gg <- function() {  g <- function() { if (FALSE) { x <- 2 } ; f <- function() { h <- function() { x() } ; h() } ; f() } ; g() } ; gg() 
h <- function() { x <- function(){2} ; f <- function() { if (FALSE) { x <- 1 } ; g <- function() { x } ; g() } ; f() } ; z <- h() ; z() 
x <- 3 ; f <- function() { assign("x", 4) ; h <- function(s=1) { if (s==2) { x <- 5 } ; x <<- 6 } ; h() ; get("x") } ; f() 
x <- 3 ; f <- function() { assign("x", 4) ; hh <- function() { if (FALSE) { x <- 100 } ; h <- function() { x <<- 6 } ; h() } ; hh() ; get("x") } ; f() 
x <- 3 ; g <- function() { if (FALSE) { x <- 2 } ; f <- function() { h <- function() { x ; hh <- function() { x <<- 4 } ; hh() } ; h() } ; f() } ; g() ; x 
f <- function() { x <- 1 ; g <- function() { h <- function() { x <<- 2 } ; h() } ; g() ; x } ; f() 
h <- new.env(parent=emptyenv()) ; assign("x", 1, h) ; exists("x", h) 
h <- new.env(parent=emptyenv()) ; assign("x", 1, h) ; exists("xx", h) 
exists("sum") 
exists("sum", inherits = FALSE) 
x <- 1; exists("x", inherits = FALSE) 
t(1:3) 
t(t(1:3)) 
t(t(t(1:3))) 
t(matrix(1:6, nrow=2)) 
t(t(matrix(1:6, nrow=2))) 
t(matrix(1:4, nrow=2)) 
t(t(matrix(1:4, nrow=2))) 
is.double(10L) 
is.double(10) 
is.double("10") 
is.numeric(10L) 
is.numeric(10) 
is.numeric(TRUE) 
is.character("hi") 
is.list(NULL) 
is.logical(NA) 
is.logical(1L) 
is.integer(1) 
is.integer(1L) 
is.complex(1i) 
is.complex(1) 
is.raw(raw()) 
sub <- function(x,y) { x - y }; sub(10,5) 
sub("a","aa", "prague alley", fixed=TRUE) 
eigen(matrix(rep(1,4), nrow=2), only.values=FALSE) 
eigen(10, only.values=FALSE) 
eigen(matrix(c(1,2,2,3), nrow=2), only.values=FALSE) 
eigen(matrix(c(1,2,3,4), nrow=2))$vectors 
eigen(matrix(c(1,2,3,4), nrow=2))$values 
eigen(matrix(c(3,-2,4,-1), nrow=2)) 
x <- 1; attributes(x) 
x <- 1; names(x) <- "hello" ; attributes(x) 
x <- 1:3 ; attr(x, "myatt") <- 2:4 ; attributes(x) 
x <- 1:3 ; attr(x, "myatt") <- 2:4 ; attr(x, "myatt1") <- "hello" ; attributes(x) 
x <- 1:3 ; attr(x, "myatt") <- 2:4 ; y <- x; attr(x, "myatt1") <- "hello" ; attributes(y) 
x <- c(a=1, b=2) ; attr(x, "myatt") <- 2:4 ; y <- x; attr(x, "myatt1") <- "hello" ; attributes(y) 
x <- c(a=1, b=2) ; attr(x, "names") 
x <- c(a=1, b=2) ; attr(x, "na") 
x <- c(a=1, b=2) ; attr(x, "mya") <- 1; attr(x, "b") <- 2; attr(x, "m") 
x <- 1:2; attr(x, "aa") <- 1 ; attr(x, "ab") <- 2; attr(x, "bb") <- 3; attr(x, "b") 
unlist(list("hello", "hi")) 
unlist(list(a="hello", b="hi")) 
x <- list(a=1,b=2:3,list(x=FALSE)) ; unlist(x, recursive=FALSE) 
x <- list(1,z=list(1,b=22,3)) ; unlist(x, recursive=FALSE) 
x <- list(1,z=list(1,b=22,3)) ; unlist(x, recursive=FALSE, use.names=FALSE) 
x <- list("a", c("b", "c"), list("d", list("e"))) ; unlist(x) 
x <- list(NULL, list("d", list(), character())) ; unlist(x) 
x <- list(a=list("1","2",b="3","4")) ; unlist(x) 
x <- list(a=list("1","2",b=list("3"))) ; unlist(x) 
x <- list(a=list(1,FALSE,b=list(2:4))) ; unlist(x) 
rev.mine <- function(x) { if (length(x)) x[length(x):1L] else x } ; rev.mine(1:3) 
a = array(1:4,c(2,2)); b = aperm(a); (a[1,1] == b[1,1]) && (a[1,2] == b[2,1]) && (a[2,1] == b[1,2]) && (a[2,2] == b[2,2]); 
a = array(1:24,c(2,3,4)); b = aperm(a); dim(b)[1] == 4 && dim(b)[2] == 3 && dim(b)[3] == 2; 
a = array(1:24,c(2,3,4)); b = aperm(a, resize=FALSE); dim(b)[1] == 2 && dim(b)[2] == 3 && dim(b)[3] == 4; 
a = array(1:24,c(2,3,4)); b = aperm(a, c(2,3,1)); a[1,2,3] == b[2,3,1]; 
a = array(1:24,c(3,3,3)); b = aperm(a, c(2,3,1)); a[1,2,3] == b[2,3,1] && a[2,3,1] == b[3,1,2] && a[3,1,2] == b[1,2,3]; 
a = array(1:24,c(3,3,3)); b = aperm(a, c(2,3,1), resize = FALSE); a[1,2,3] == b[2,3,1] && a[2,3,1] == b[3,1,2] && a[3,1,2] == b[1,2,3]; 
a = array(1:24,c(2,3,4)); b = aperm(a, c(2,3,1), resize = FALSE); a[1,2,3] == b[2,1,2]; 
aperm(c(1,2,3)); 
aperm(array(1,c(3,3,3)), c(1,2)); 
aperm(array(1,c(3,3,3)), c(1,2,1)); 
aperm(array(1,c(3,3,3)), c(1,2,0)); 
aperm(array(1:27,c(3,3,3)), c(1+1i,3+3i,2+2i))[1,2,3] == array(1:27,c(3,3,3))[1,3,2]; 
a = colSums(matrix(1:12,3,4)); is.null(dim(a)); 
a = colSums(matrix(1:12,3,4)); length(a) == 4; 
a = colSums(matrix(1:12,3,4)); a[1] == 6 && a[2] == 15 && a[3] == 24 && a[4] == 33; 
a = colSums(array(1:24,c(2,3,4))); d = dim(a); d[1] == 3 && d[2] == 4; 
a = colSums(array(1:24,c(2,3,4))); length(a) == 12; 
a = colSums(array(1:24,c(2,3,4))); a[1,1] == 3 && a[2,2] == 19 && a[3,3] == 35 && a[3,4] == 47; 
a = rowSums(matrix(1:12,3,4)); is.null(dim(a)); 
a = rowSums(matrix(1:12,3,4)); length(a) == 3; 
a = rowSums(matrix(1:12,3,4)); a[1] == 22 && a[2] == 26 && a[3] == 30; 
a = rowSums(array(1:24,c(2,3,4))); is.null(dim(a)); 
a = rowSums(array(1:24,c(2,3,4))); length(a) == 2; 
a = rowSums(array(1:24,c(2,3,4))); a[1] == 144 && a[2] == 156; 
f<-function(i) { if(i<=1) 1 else i*Recall(i-1) } ; f(10) 
f<-function(i) { if(i<=1) 1 else i*Recall(i-1) } ; g <- f ; f <- sum ; g(10) 
f<-function(i) { if (i==1) { 1 } else if (i==2) { 1 } else { Recall(i-1) + Recall(i-2) } } ; f(10) 
Recall(10) 
x <- 1:6 ; crossprod(x) 
x <- 1:2 ; crossprod(t(x)) 
crossprod(1:3, matrix(1:6, ncol=2)) 
crossprod(t(1:2), 5) 
crossprod(c(1,NA,2), matrix(1:6, ncol=2)) 
sort(c(1L,10L,2L)) 
sort(c(3,10,2)) 
sort(c(1,2,0/0,NA)) 
sort(c(2,1,0/0,NA), na.last=NA) 
sort(c(3,0/0,2,NA), na.last=TRUE) 
sort(c(3,NA,0/0,2), na.last=FALSE) 
sort(c(3L,NA,2L)) 
sort(c(3L,NA,-2L), na.last=TRUE) 
sort(c(3L,NA,-2L), na.last=FALSE) 
sort(c(a=NA,b=NA,c=3,d=1),na.last=TRUE, decreasing=TRUE) 
sort(c(a=NA,b=NA,c=3,d=1),na.last=FALSE, decreasing=FALSE) 
sort(c(a=0/0,b=1/0,c=3,d=NA),na.last=TRUE, decreasing=FALSE) 
sort(double()) 
sort(c(a=NA,b=NA,c=3L,d=-1L),na.last=TRUE, decreasing=FALSE) 
sort(c(3,NA,1,d=10), decreasing=FALSE, index.return=TRUE) 
sort(3:1, index.return=TRUE) 
cbind(1:3,1:3) 
cbind() 
m <- matrix(1:6, nrow=2) ; cbind(11:12, m) 
cbind(list(1,2), TRUE, "a") 
cbind(1:3,1:2) 
cbind(1:3,2) 
